from __future__ import annotations

import asyncio
import queue
import threading

from addon import HistoryAddon
from models import FlowRecord


class ProxyEngine:
    """Runs mitmproxy's DumpMaster on a background thread with its own asyncio
    event loop (required -- the GUI owns the main thread). CA cert is
    auto-generated by mitmproxy on first run under --confdir (default
    ~/.mitmproxy/mitmproxy-ca-cert.pem) -- that's the cert the user installs
    into their browser/OS trust store once."""

    def __init__(self) -> None:
        self.out_queue: "queue.Queue[FlowRecord]" = queue.Queue()
        self._thread: threading.Thread | None = None
        self._master = None
        self._loop: asyncio.AbstractEventLoop | None = None
        self.error: Exception | None = None
        self.confdir: str | None = None

    @property
    def running(self) -> bool:
        return self._thread is not None and self._thread.is_alive()

    def start(self, host: str, port: int, confdir: str) -> None:
        if self.running:
            return
        self.error = None
        self.confdir = confdir
        ready = threading.Event()
        self._thread = threading.Thread(
            target=self._run, args=(host, port, confdir, ready), daemon=True
        )
        self._thread.start()
        ready.wait(timeout=15)

    def _run(self, host: str, port: int, confdir: str, ready: threading.Event) -> None:
        from mitmproxy import options
        from mitmproxy.tools.dump import DumpMaster

        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        self._loop = loop
        try:
            opts = options.Options(listen_host=host, listen_port=port, confdir=confdir)
            master = DumpMaster(opts, loop=loop, with_termlog=False, with_dumper=False)
            master.addons.add(HistoryAddon(self.out_queue))
            self._master = master
            ready.set()
            loop.run_until_complete(master.run())
        except BaseException as exc:  # noqa: BLE001
            # Must be BaseException, not Exception: mitmproxy's own
            # ErrorCheck addon reports fatal startup failures (e.g. the
            # port is already taken by Burp/another proxy) by calling
            # sys.exit(), which raises SystemExit -- a plain `except
            # Exception` would silently swallow that and leave `running`
            # False with `error` never set, i.e. the GUI would have no way
            # to tell the user why it didn't come up.
            self.error = exc
            ready.set()
        finally:
            loop.close()

    def stop(self) -> None:
        if self._master is not None and self._thread is not None and self._thread.is_alive():
            try:
                self._master.shutdown()
            except RuntimeError:
                pass  # engine's event loop already closed (it died on its own, e.g. failed to bind)
        if self._thread is not None:
            self._thread.join(timeout=10)
        self._master = None
        self._thread = None

    def drain(self, max_items: int = 200) -> list[FlowRecord]:
        items: list[FlowRecord] = []
        for _ in range(max_items):
            try:
                items.append(self.out_queue.get_nowait())
            except queue.Empty:
                break
        return items
